name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: `1.21`
      - name: Create .env
        run: make env
      - name: Install dependencies
        run: go mod download
      - name: Start db
        run: make start-db
      - name: Test
        run: make test
